// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"EliMZ_Book","status":true,"description":"♦5.4.3♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"EliMZ_ButtonCommonEvents","status":true,"description":"♦5.2.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[\"{\\\"key\\\":\\\"backspace\\\",\\\"id\\\":\\\"1\\\",\\\"isParallel\\\":\\\"false\\\",\\\"overwrite\\\":\\\"false\\\"}\"]","presetKeysGamePad":"[]"}}
];
