// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EliMZ_Book","status":true,"description":"♦5.3.0♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"disableEffekseer\":\"false\",\"styleOverflow\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"false\",\"quickRestart\":\"true\"}"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"EliMZ_MoveChoices","status":true,"description":"♦5.0.0♦ Change the position of the Choice Window.","parameters":{"okDelay":"0"}},
{"name":"Cae_DashOpts","status":true,"description":"v1.0 - Dash options: speed, frame-skip, event dashing, etc.","parameters":{"Dash Extra Speed":"0.00","Skip Standing Frame":"false","Add Save Data":"false","--- Advanced ---":"","Property: dashSpeed":"_dashSpeed","Property: isDashing":"_isDashing","Property: Save":"Cae_DashOpts"}},
{"name":"HIME_TimedChoiceSelection","status":true,"description":"v1.1 - Set a timer that automatically selects a choice for the\r\nplayer when the timer expires.","parameters":{}}
];
