// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EliMZ_Book","status":true,"description":"♦5.3.0♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"EliMZ_ButtonCommonEvents","status":false,"description":"♦5.2.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[\"{\\\"key\\\":\\\"backspace\\\",\\\"id\\\":\\\"1\\\",\\\"isParallel\\\":\\\"true\\\",\\\"overwrite\\\":\\\"true\\\"}\"]","presetKeysGamePad":"[]"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"EliMZ_MoveChoices","status":true,"description":"♦5.0.0♦ Change the position of the Choice Window.","parameters":{"okDelay":"0"}},
{"name":"Cae_DashOpts","status":true,"description":"v1.0 - Dash options: speed, frame-skip, event dashing, etc.","parameters":{"Dash Extra Speed":"0.00","Skip Standing Frame":"false","Add Save Data":"false","--- Advanced ---":"","Property: dashSpeed":"_dashSpeed","Property: isDashing":"_isDashing","Property: Save":"Cae_DashOpts"}}
];
